// AUTO-GENERATED by scripts/generate-schema.ts from domains/*.json - do not edit by hand.
// Regenerate with `bun run generate:schema`.
import type { DomainSchema } from "./schema-core";

export type DomainName = "music" | "shop";

export const DOMAINS: Record<DomainName, DomainSchema> = {
  "music": {
    name: "music",
    entityListLabel: "tracks, playlists, artists, genres, or listeners on a music streaming service",
    outOfScopeDescription: "anything unrelated to searching/filtering tracks, playlists, artists, genres, or listeners on a music streaming service - e.g. general knowledge, cooking, weather, small talk",
    entityDescriptions: {
      "track": "Songs available to stream",
      "playlist": "User-curated collections of tracks",
      "artist": "Musicians and bands with tracks on the service",
      "genre": "Musical genres tracks are categorized under",
      "listener": "Registered listeners / accounts on the service",
    },
    schema: {
      "track": {
        "title": { type: "string", description: "the track's title" },
        "duration_seconds": { type: "number", description: "the track's length in seconds" },
        "release_date": { type: "date", description: "when the track was released" },
        "explicit": { type: "boolean", description: "whether the track has explicit content" },
      },
      "playlist": {
        "name": { type: "string", description: "the playlist's name" },
        "created_by_me": { type: "self", description: "the caller's own playlists - 'my playlists', 'playlists I made', no other person involved" },
        "track_count": { type: "number", description: "how many tracks the playlist has" },
        "created_at": { type: "date", description: "when the playlist was created" },
      },
      "artist": {
        "name": { type: "string", description: "the artist's name" },
        "verified": { type: "boolean", description: "whether the artist's profile is verified" },
        "monthly_listeners": { type: "number", description: "how many monthly listeners the artist has" },
      },
      "genre": {
        "name": { type: "string", description: "the genre's name" },
        "track_count": { type: "number", description: "how many tracks belong to the genre" },
      },
      "listener": {
        "name": { type: "string", description: "the listener's name" },
        "email": { type: "email", description: "the listener's email address" },
        "premium": { type: "boolean", description: "whether the listener has a premium subscription" },
        "signed_up_at": { type: "date", description: "when the listener signed up" },
      },
    },
  },
  "shop": {
    name: "shop",
    entityListLabel: "products, customers, orders, categories, or reviews in an online shop",
    outOfScopeDescription: "anything unrelated to searching/filtering products, customers, orders, categories, or reviews in an online shop - e.g. general knowledge, cooking, weather, small talk",
    entityDescriptions: {
      "product": "Products for sale in the shop",
      "customer": "Registered customers of the shop",
      "order": "Orders placed by customers",
      "category": "Product categories in the shop's catalog",
      "review": "Customer reviews left on products",
    },
    schema: {
      "product": {
        "name": { type: "string", description: "the product's name" },
        "sku": { type: "string", description: "the product's SKU / stock code" },
        "price": { type: "number", description: "the product's price" },
        "in_stock": { type: "boolean", description: "whether the product is currently in stock" },
        "added_at": { type: "date", description: "when the product was added to the catalog" },
      },
      "customer": {
        "name": { type: "string", description: "the customer's name" },
        "email": { type: "email", description: "the customer's email address" },
        "signed_up_at": { type: "date", description: "when the customer signed up" },
      },
      "order": {
        "placed_by_me": { type: "self", description: "the caller's own orders - 'my orders', 'orders I placed', no other person involved" },
        "status": { type: "string", description: "the order's status, e.g. pending, shipped, delivered, cancelled" },
        "total": { type: "number", description: "the order's total price" },
        "placed_at": { type: "date", description: "when the order was placed" },
      },
      "category": {
        "name": { type: "string", description: "the category's name" },
        "product_count": { type: "number", description: "how many products belong to the category" },
      },
      "review": {
        "written_by_me": { type: "self", description: "the caller's own reviews - 'my reviews', 'reviews I wrote', no other person involved" },
        "rating": { type: "number", description: "the review's star rating" },
        "verified_purchase": { type: "boolean", description: "whether the review is from a verified purchase" },
        "created_at": { type: "date", description: "when the review was written" },
      },
    },
  },
};

export const DEFAULT_DOMAIN: DomainName = "music";
