// Regenerates src/schema.generated.ts from every domains/*.json config
// (excluding *.examples.json, which the API loads directly at runtime).
// Run via `bun run generate:schema`.
//
// Why codegen instead of loading the JSON at runtime: DomainName is a
// literal-union type, used as `Record<DomainName, X>` for the top-level
// domain registry - that gives the compiler exhaustiveness checking on
// which domains exist. EntityName itself is NOT a literal union anymore
// (different domains have entirely different entities), so it's just
// `string` - see schema-core.ts. Adding a domain still means regenerating
// and rebuilding, not just dropping in a new JSON file.
import { z } from "zod";
import { readdir } from "node:fs/promises";

const FieldConfig = z.object({
  type: z.enum(["string", "number", "date", "email", "boolean", "self"]),
  description: z.string(),
});

const EntityConfig = z.object({
  description: z.string(),
  fields: z.record(z.string(), FieldConfig),
});

const DomainConfig = z.object({
  domain: z.string(),
  entityListLabel: z.string(),
  outOfScopeDescription: z.string(),
  entities: z.record(z.string(), EntityConfig),
});

const domainsDir = process.argv[2] ?? "domains";
const outPath = "packages/domain/src/schema.generated.ts";

const files = (await readdir(domainsDir)).filter((f) => f.endsWith(".json") && !f.endsWith(".examples.json"));
if (files.length === 0) {
  throw new Error(`no domain config files found in ${domainsDir}/ (expected *.json, not *.examples.json)`);
}

function tsStringLiteral(s: string): string {
  return JSON.stringify(s);
}

const domains: { name: string; config: z.infer<typeof DomainConfig> }[] = [];
for (const file of files.sort()) {
  const raw = await Bun.file(`${domainsDir}/${file}`).json();
  const config = DomainConfig.parse(raw);
  domains.push({ name: config.domain, config });
}

const domainNameUnion = domains.map((d) => tsStringLiteral(d.name)).join(" | ");

const domainEntries = domains
  .map(({ name, config }) => {
    const entityNames = Object.keys(config.entities);
    if (entityNames.length === 0) {
      throw new Error(`domain "${name}": "entities" must have at least one entry`);
    }
    const entityDescriptions = entityNames
      .map((entityName) => `      ${tsStringLiteral(entityName)}: ${tsStringLiteral(config.entities[entityName]!.description)},`)
      .join("\n");
    const schemaEntries = entityNames
      .map((entityName) => {
        const fields = config.entities[entityName]!.fields;
        const fieldEntries = Object.entries(fields)
          .map(([fieldName, def]) => `        ${tsStringLiteral(fieldName)}: { type: ${tsStringLiteral(def.type)}, description: ${tsStringLiteral(def.description)} },`)
          .join("\n");
        return `      ${tsStringLiteral(entityName)}: {\n${fieldEntries}\n      },`;
      })
      .join("\n");

    return `  ${tsStringLiteral(name)}: {
    name: ${tsStringLiteral(name)},
    entityListLabel: ${tsStringLiteral(config.entityListLabel)},
    outOfScopeDescription: ${tsStringLiteral(config.outOfScopeDescription)},
    entityDescriptions: {
${entityDescriptions}
    },
    schema: {
${schemaEntries}
    },
  },`;
  })
  .join("\n");

const output = `// AUTO-GENERATED by scripts/generate-schema.ts from ${domainsDir}/*.json - do not edit by hand.
// Regenerate with \`bun run generate:schema\`.
import type { DomainSchema } from "./schema-core";

export type DomainName = ${domainNameUnion};

export const DOMAINS: Record<DomainName, DomainSchema> = {
${domainEntries}
};

export const DEFAULT_DOMAIN: DomainName = ${tsStringLiteral(domains[0]!.name)};
`;

await Bun.write(outPath, output);
console.log(`wrote ${outPath} - domains: ${domains.map((d) => d.name).join(", ")}`);
